version: '3'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: developer
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: devpassword
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:25000:5432"
  
  redis:
    image: redis:latest
    ports:
      - "127.0.0.1:25100:6379"
    volumes:
      - redis-data:/data
    command: redis-server --save ""

  api:
    build: .
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=postgresql://developer:devpassword@postgres:5432/developer
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./app:/app  # 개발 시 코드 변경 실시간 반영

volumes:
  postgres-data:
    driver: local
  redis-data:
    driver: local